version: "3.8"

services:
  mongodb:
    container_name: mongo-database
    image: mongo
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    restart: always
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - .:/app
