version: "3.8"

services:
  backend:
    container_name: image-service
    restart: always
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  mongodb:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27017:27017"
